---
sudo: required
services:
  - docker

branches:
  only:
    - master
    - k8s

env:
  global:
    # DOCKER_EMAIL
    - secure: "ZpcxMV13K++KFxYve6JcNgTWlBvDhi2nhNa1oC89OenRwYt+eXCNOEHBHADuHlQyrs3+KNaRUUNLVgEWTcdjUos8x9krVqKIXoagl9d5SlkLTOkhmhbAxwueBL/nlL2aHYiQ47zCbj7gXAfOf4rt5WNI00tyTha0jnXbNKX7MMPTsXwbe/Y/Zdae/hYsxuentbZe3uApVGzFl1mX66DWnvOLI19u8ijD2+DLC91EJvLsmOX7brglv4pgwyhFbBpwtVoeOckb7NJbP37AMsp79M2UBdLtu7oi8ZEqxP6HLAHDobCZZQx/yNUMl2RLw5Kk72j+M+lQmGcJeU9TNH0ckdObeVFheXw18Tx+1QWq63jG1MMi9w+nG/bML70LkkXbODkwDFzQ9uR9CfIcfb+epmMdPS0UCP5x4++KsKGZDfyoj9jU8gvDWp14u2FGxQbs5w/GKMvyGJsFR3uEGb1tHtLm2AQsgByyfALOVpZzYgMh0L6rNQEhLjlG2W2IkilAaod9nHigfCnW/rqaKHEnT4p2JNSUMjs2Ch6w918bK65OuM9W+wE24shfWD/8jmtkUU5aONhJRWsjROMBRsvCHhtyGF/TBMRdl0XuenzSQaSuTkOvKmJoklUvf331Y+iMdnGX2P6eC8FQ3Z7o7gIpKW/Pewy2eH967Rx/ElCbZWw="
    # DOCKER_USER
    - secure: "lGGYfcPw08Dj3kpiO6RGEn9Q3ahpRTS3EhN84Ja5rrIvTPQ0RSOLungnpLjMuSV4I6H2NLYbpp5IjtG4wmA+RmHZHV3998dUJYqL1FLimaPurUFURTZCiLWGHO+81SXKOS2jhIqBMpn5veIWCKHeokfXBr0FUn35Xm/hJll8JMOZh3+8L0b7u161A9GJinYuQ/OVMPUmqS8a5eVot2Vl7afJArDT25defr3V3d9XmVw4Dk75Z2nzNyyyNL/N+r3pvz7ahegFbq2Jo+z+/hW6Tsb3FAlS19P8rC/sw9q+o6FK3wSQyg4+RaBT7iJ01A8BwPIC99UAeeDMbACa7tBTKhbTeemDWZ4LczCsTHDey3Tg+tfYyTFCvx0E7LJ8KPRStRnPK5UgYby7QxJ1i5azOYwqYNfBzA170sfC0apyGWkm8IOuxmwDjVpsLkbWTqJec1gQdA21eJE7pM9fqzLI2GEnQqUZmE/f/ftkh+RONZP7neeRk4bv5WQRDtMaHd7hgSsUsygDpAJLc2Z0nxPOJRwIKzQ05UucqqW+1JfNXhOAtOAm+JydHzXgEVZa9alf4mpbbcTbWEw5QHPNJaW7UHbPJVD3siJDT1bLLMFroW/ZSiq0Uylns+Cg2YpJ9X0UXxwNztYfBolJ2MkgdJIWqr4Jek7cVgFx077C79+YNwQ="
    # DOCKER_PASS
    - secure: "lt1IYf5TNWSBaoohBnppzwbDzV8KRam0ZHBdBTzZ5zhuKBxjafB5H0YQsBdwet/NzloYytNlbKirRArIUYw1UuTN2Nty8q3tNyEMFZoOATPQhiAiHIuu61Lz8OBilbCyvYWkK78APuY/1OHeEa/o5xUUk+btBZcFHPrsd+MkCPXcLC5cNB08oLUK3KgBmPXhbd/3oB+eXfd8Q2ZLynbD1QgqDmeUT+nsFlhVEbBf7ZFt+KjUKr3F0VimTF8CdOPH04sNGgRPrMXUxayLVWeAkh1KYMV+K2gkWjkLOqh5WOgZ+dU+Pu7F/89Pzgl9kHdseddrFCttS4QTdF18sdAf//HnjC8WPLBH7S1h5cBWJo4Vei+QGfayDJLrYDnQu1Lj1gNo+k2DClyReX8EhOHN/nTBuIJ/7/axYWlyfzO8xd3WZDgaZsKhOwWd4mKAmHkTJjEyoR46JtJgOZOo99YeC8x3mvDjj8iNVF+AWf7HBAaHtI0mlpK35uh+8UO5ZeGXtUrB/OAV6Z1fecPVbqpoxQ8L/pCkNpe05zZVuY3f50nLg+TqqhZYmhDO7N9c3mT6vkZoekuDresBN+gt5BfxU89oKfhBwAtDA/jI08mS3SFnxXLXRjwTAaLzAn5ehe+9LzloheCWO9RzN0936XlHDZ/8BAPs+aqK9huLYjLQrkg="
    - DOCKER_REPO=spreadspace/onion-service

before_script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:latest

script:
  ### build the new images
  - docker build -t $DOCKER_REPO:$TRAVIS_BUILD_NUMBER .

after_success:
  - >-
    if [ "${TRAVIS_BRANCH}" = master ]; then
      DOCKER_TAG="latest"
    else
      DOCKER_TAG="${TRAVIS_BRANCH}"
    fi
  - docker tag $DOCKER_REPO:$TRAVIS_BUILD_NUMBER $DOCKER_REPO:$DOCKER_TAG
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:$DOCKER_TAG
